### ISSUE TITLE
ha-blueiris crashing Blue Iris?

### ISSUE THREAD

**Issue by autumnwalker** [elad-bar/ha-blueiris#107]
After integrating ha-blueiris my Blue Iris application started crashing. Would crash multiple times per day. I've been going through troubleshooting with BI and they are unable to find issue with their software.

On a whim I disabled ha-blueiris and the crashing stopped, my BI app / server is completely stable again and has been up for five days without crashing.

I'm not suggesting 100% there is something with this integration, but I'm not sure where to start. There is certainly correlation that when I disable this integration the crashing stops.

Running:
- ha-blueiris 1.0.5
- Home Assistant core-2021.03.02 (although this has been happening across the last several updates)
- Blue Iris 5.3.9.16 (crashing has occurred on different versions as well)

Thoughts?

**Comment by autumnwalker** [comment]
After doing some more testing - it seems like a straight generic camera integration is crashing BI as well.

How is this addon adding streams (which URI)?

**Comment by elad-bar** [comment]
I had the same issue of crashes since that version of BI server, it caused by memory leak while accessing the streams, it happens from time to time with BI new releases, if you will try to open the streams for all your cameras you will see that it has nothing to do with the ha component

My solution for that is switching to another NVR software,
Over the last week I'm working with Shinobi Video and it works very well,
I'm finalizing the custom component for that and will post at ha forum the new component

It basically means I'm not going to maintain that component unless BI server will get more stablized (and not just for 3 months)

Thanks

**Comment by autumnwalker** [comment]
Just wanted to update this thread to give some clarity / resolution to anyone who may view. 

We've traced my issue to be specific to my EZVIZ DB1C doorbell camera. Only when this camera is streaming RTSP via Blue Iris does BI crash. When other cameras stream RTSP via Blue Iris to Home Assistant, Blue Iris is stable. 

There is something about the DB1C causing the stability problem.
