### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by wifispray** [elad-bar/ha-blueiris#165]
Is it possible to define / pull the presets from blue iris into HA and show within a lovelace?

**Comment by kramttocs** [comment]
Yes, you can create buttons that would then call the Move To Preset service. To my knowledge, there isn't a way to pull back what preset numbers are 'set' for a camera.
The alternative would be creating 10 (40 would be too many I think) buttons for each camera by default.
Buttons would be better than toggles because the camera could be moved manually via the PTZ arrows so the toggle could easily be wrong even if it shows 'on'.

**Comment by wifispray** [comment]
Is there a guide to doing this?

**Comment by kramttocs** [comment]
No, well at least not within the BI NVR doc as it's more HA than BI.
To clarify, the 'alternative' would be something done in this integration though I am not sure it's the best approach. Will have to think on it.

For the first though that would be something you can do. 
At a high level it would be:
1. Create a helper button for the profiles you want. You could make a button move multiple cameras (doesn't even have to be the same present # they are moving to) or make it 1:1
2. Create an automation that is triggered by the button press
3. In that automation you can call the service and specify the camera and preset value. Here is where you could call the service multiple times if you want to move a number of cameras at once.

Note that the service also accepts Blue Iris camera groups if you use those. In this manner you could call a group to simplify things but it would send the same preset numerical value to all of them.

Hope that helps.
